import SidebarComponent from "@/components/SidebarComponent";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import ListBoardComponentHeader from "@/components/ListBoardComponentHeader";
import AuthProvider from "./api/auth/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay w-full flex gap-5 h-screen overflow-y-hidden transition-all">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
